services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FIAP_api
    restart: on-failure
    networks:
      - FIAP-network
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:16.2
    container_name: FIAP_postgresql
    restart: on-failure
    ports:
      - 5433:5432
    networks:
      - FIAP-network
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 756M

networks:
  FIAP-network:
    driver: bridge