apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodieflow-order
  labels:
    app: foodieflow-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodieflow-order
  template:
    metadata:
      name: foodieflow-order
      labels:
        app: foodieflow-order
    spec:
      automountServiceAccountToken: false
      containers:
        - name: foodieflow-order
          image: us-west1-docker.pkg.dev/foodieflow/ff-order/app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: ${{ secrets.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: ${{ secrets.POSTGRES_PASSWORD }}
            - name: POSTGRES_DB
              value: ${{ secrets.POSTGRES_DB }}
            - name: POSTGRES_HOST
              value: ${{ secrets.POSTGRES_HOST }}
            - name: POSTGRES_PORT
              value: ${{ secrets.POSTGRES_PORT }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
      restartPolicy: Always
