apiVersion: v1
kind: Service
metadata:
  name: foodieflow-order-service
  labels:
    app: foodieflow-order
spec:
  type: LoadBalancer
  selector:
    app: foodieflow-order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080